env_type: 'gym' # gym, custom
env_name: 'CartPole-v1' # if custom anyname is OK
custom_env: 'stock_env.py'

nn_mod: 'actor_critic_nn' # must match with network_models counts
# nn_mod: 'actor_critic_nn' # must match with network_models counts
network_models: ['ActorCritic']
optimizer: 'adam'
learning_rate: 1e-4
epochs: 1000
flip_res: True # 
multi_procs: True
num_multi_procs: 12
loss_fn: 'actor-critic' # actor-critic, 
state_norm: True
gamma: 0.9
clc: 0.1

n_step_mode: True
n_step: 100


replay_mode: True
ep_buffer_size: 200

# exploration for 
expolration: True
epsilon: 0.2

exp_priority: False
priority_level: 5

# shuffle experience
sampled_batch: False
batch_size: 50