env_type: 'gym' # gym, custom
env_name: 'CartPole-v1' # if custom anyname is OK
custom_env: 'stock_env.py'

nn_mod: 'actor_critic_nn' # must match with network_models counts
# nn_mod: 'actor_critic_nn' # must match with network_models counts
network_models: ['ActorCritic']
optimizer: 'adam'
learning_rate: 1e-4
epochs: 1000
flip_res: True # 
n_step_mode: True
n_step: 100
multi_procs: True
num_multi_procs: 12
loss_fn: 'actor-critic' # actor-critic, 
state_norm: True